
-- MySQL Script generated by MySQL Workbench
-- Thu Sep 27 15:29:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `id_veiculo` INT NOT NULL AUTO_INCREMENT,
  `modelo_veiculo` VARCHAR(100) NOT NULL,
  `marca_veiculo` VARCHAR(100) NOT NULL,
  `ano_fabricacao_veiculo` INT(4) NOT NULL,
  `ano_modelo_veiculo` INT(4) NOT NULL,
  `placa_veiculo` VARCHAR(10) NULL,
  `chassi_veiculo` VARCHAR(20) NULL,
  `valor_veiculo` DECIMAL(10,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_veiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendedor` (
  `id_vendedor` INT NOT NULL AUTO_INCREMENT,
  `nome_vendedor` VARCHAR(100) NOT NULL,
  `num_carros_vendidos_vendedor` INT(5) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_vendedor`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`venda_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda_veiculo` (
  `id_venda_veiculo` INT NOT NULL AUTO_INCREMENT,
  `veiculo_id_veiculo` INT NOT NULL,
  `vendedor_id_vendedor` INT NOT NULL,
  `data_venda_veiculo` DATE NOT NULL,
  `valor_venda_veiculo` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `valor_comissao_venda_veiculo` DECIMAL(10,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_venda_veiculo`),
  FOREIGN KEY (`veiculo_id_veiculo`) REFERENCES `mydb`.`veiculo` (`id_veiculo`),
  FOREIGN KEY (`vendedor_id_vendedor`) REFERENCES `mydb`.`vendedor` (`id_vendedor`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

# Inserir valores na tabela veiculo

INSERT INTO `mydb`.`veiculo`
(`id_veiculo`,
`modelo_veiculo`,
`marca_veiculo`,
`ano_fabricacao_veiculo`,
`ano_modelo_veiculo`,
`placa_veiculo`,
`chassi_veiculo`,
`valor_veiculo`)
VALUES
(1, 'Civic', 'Honda', 2017, 2018, 'HJA-9831', 99933182, 94374),
(2, 'Corolla', 'Toyota', 2016, 2016, 'HJC-9931', 99398103, 86346),
(3, 'Camaro', 'Chevrolet', 2014, 2015, 'HAV-8829', 99288131, 186711),
(4, 'Freemont', 'Fiat', 2011, 2012, 'FLJ-3128', 77312993, 52660),
(5, 'HRV', 'Honda', 2016, 2016, 'FAY-8221', 88331293, 84164);

# Inserir valores na tabela Vendedor

INSERT INTO `mydb`.`vendedor`
(`id_vendedor`,
`nome_vendedor`,
`num_carros_vendidos_vendedor`)
VALUES
(1, 'Carlos', 1),
(2, 'Joaquim', 1),
(3, 'Júlia', 0),
(4, 'Letícia', 0),
(5, 'Roberto', 0);

delimiter $$
CREATE PROCEDURE vender_veiculo(IN veiculo INT, IN vendedor INT, OUT valor_comissao_venda DECIMAL)
BEGIN
SET @dt_venda_veiculo = curdate();
SET @valor = 0;
SELECT valor_veiculo INTO @valor FROM veiculo where id_veiculo = veiculo;
SET @valor_comissao_venda_veiculo = (@valor * 0.2);
SELECT @valor_comissao_venda_veiculo INTO valor_comissao_venda;
INSERT INTO venda_veiculo (veiculo_id_veiculo, vendedor_id_vendedor,  data_venda_veiculo, 
valor_venda_veiculo, valor_comissao_venda_veiculo)
VALUE (veiculo, vendedor,  @dt_venda_veiculo, @valor, @valor_comissao_venda);
END $$
delimiter ;


